// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMg2OfMAfAbWOtDcDwQ2pIi5z5X3vfBWY',
    appId: '1:852705649694:web:da42b919226ff456593a0f',
    messagingSenderId: '852705649694',
    projectId: 'sirat-ezan-vakti-2026',
    authDomain: 'sirat-ezan-vakti-2026.firebaseapp.com',
    storageBucket: 'sirat-ezan-vakti-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYANJTFjiUqG1t-i1yHiPHSFwsWBU15lE',
    appId: '1:852705649694:android:00f1dd7696319667593a0f',
    messagingSenderId: '852705649694',
    projectId: 'sirat-ezan-vakti-2026',
    storageBucket: 'sirat-ezan-vakti-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwb5FX8_LZv4VoWEgms1pDVxmRUD2b8vM',
    appId: '1:852705649694:ios:e9b24c094d7572e1593a0f',
    messagingSenderId: '852705649694',
    projectId: 'sirat-ezan-vakti-2026',
    storageBucket: 'sirat-ezan-vakti-2026.firebasestorage.app',
    iosBundleId: 'com.sirat.sirat',
  );
}
